apiVersion: v1
stringData:
  token: pat.L_gdXZz1QDulufcvr1KCXw.68822fe9d3e5af41593d9272.6Buey2Rq1xFoHmVtFMSX
kind: Secret
metadata:
  name: harness-api-key
  namespace: harness-autostopping
type: Opaque

